version: '3'
services:
  mongodb:
    image: mongo:3.4
    volumes:
      - /tmp/mongo:/data
  talkbot:
    image: nimnull/talkbot:latest
    command: /bin/sh -c "python setup.py install && talk_bot run -c /srv/config.json"
    volumes:
      - .:/srv
      - /etc/letsencrypt/archive/talkbot1.mediasapiens.org:/etc/certs:ro
    links:
      - mongodb
    ports:
      - "0.0.0.0:443:443/tcp"
