version: '3'
services:
  mongodb:
    image: mongo:3.4
    volumes:
      - /opt/mongo:/data
  talkbot:
    image: python:3.6-alpine
    command: talk_bot run -c /srv/config.json
    volumes:
      - .:/srv
    links:
      - mongodb
    ports:
      - "443:443"
